### PR TITLE
Proposition of OSCore Store

### PR DESCRIPTION
**Pull request by Michal-Wadowski**
Example implementation of OSCore Store to debate on

### CODE REVIEW

**Comment by Michal-Wadowski** [comment]
Note that I changed FileSecurityStore from instead extending of InMemorySecurityStore to composite with EditableSecurityStore. It allows me to inject OSCoreSecurityStore as a middleware.

I also have a question: do we need separate OSCore Security Store? Or maybe it should be integral part of InMemorySecurityStore/FileSecurityStore/RedisSecurityStore because it will be always OSCore support (it's not just an option).

Another question: what name we should use for classes? OSCoreXXX or OscoreXXX? Because in project we have mix of these names we should take one strategy name. Similar problem is with other classes like LwM2mXXX/Lwm2mXXX

**Comment by sbernard31** [comment]
(I begin by the easy question)

>  LwM2mXXX/Lwm2mXXX

I don't like so much the `LwM2mXXX` prefix. I would prefer `Lwm2mXXX` but that was the chosen one when I integrate the project. So `Lwm2mXXX` should be not be used. Is there so class which uses this prefix ? 

> OSCoreXXX or OscoreXXX

I have no strong opinion. The "real" way to write oscore should be OSCORE (https://datatracker.ietf.org/doc/html/rfc8613)
So I guess maybe  OSCoreXXX does not make so much sense. so maybe OscoreXXX is better.

**Comment by Michal-Wadowski** [comment]
> Is there so class which uses this prefix ?

There are LwM2MResourceTest and Lwm2mEndpointContextMatcher which doesn't fit into pattern. But most of classes are LwM2mXXX indeed. I just noticed Lwm2mEndpointContextMatcher class by accident but I didn't noticed that is rare case.

**Comment by sbernard31** [comment]
@Michal-Wadowski, I think we can close this one ?

About the LwM2mXXX/Lwm2mXXX wording, please do not hesitate to create a dedicated issue where you list the problematic name.

**Comment by sbernard31** [comment]
I close it as Oscore Store is now implemented with  #1212.

Some of your ideas was reused (like OscoreIdentity)

@Michal-Wadowski thx for that :pray:

**Pull request closed without merging**
