### PR TITLE
Protect security object from invalid access.

### PR DESCRIPTION
**Pull request by boaks**
Protect security object from access of DM server.
Protection is implemented in CoAP method mapping to allow the internal use of read/write operations as in ServersInfoExtractor.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by sbernard31** [comment]
Ideally, the responsibility of `ObjectResource` should be to translate CoAP request in LWM2M request. 
The idea is to keep a minimum of LWM2M logic in `leshan-server-cf` which is dependent of `californium`.

But to do that we should move "identity checks"  in `BaseObjectEnabler`. This means that it needs access to `BootstrapHandler`  :-/

About return codes, maybe `4.01 Unauthorized` is more adapted, what do you think ?

**Comment by boaks** [comment]
The issue for me was:
- read is never allowed from outside
- but used from inside (`ServersInfoExtractor`).

So solving it with "identity check" would require to introduce a "SYSTEM" identity to allow such internal operations. And that seems to me a little "overdone".
Therefore I chose the `ObjectResource` also as point of "external use", leave the `BaseObjectEnabler` for easy internal use.

**Comment by sbernard31** [comment]
We already face this kind of problem, currently we consider [null identity as a "SYSTEM" identity](https://github.com/eclipse/leshan/blob/master/leshan-client-core/src/main/java/org/eclipse/leshan/client/resource/ObjectEnabler.java#L133).

**Comment by boaks** [comment]
About return codes, maybe 4.01 Unauthorized is more adapted, what do you think ? 

I chose 4.04 Not Found, because, if the object is not reported in the registration, its not there :-).

**Comment by boaks** [comment]
We already face this kind of problem, currently we consider null identity as a "SYSTEM" identity.

OK, this makes it easier ...

**Comment by sbernard31** [comment]
Ok for 4.04 Not Found.

**Comment by boaks** [comment]
We already face this kind of problem, currently we consider null identity as a "SYSTEM" identity.

Ok, but

    public static Identity extractIdentity(CoapExchange exchange) {
        InetSocketAddress peerAddress = new InetSocketAddress(exchange.getSourceAddress(), exchange.getSourcePort());

        Principal senderIdentity = exchange.advanced().getRequest().getSenderIdentity();
        if (senderIdentity != null) {
            if (senderIdentity instanceof PreSharedKeyIdentity) {
                return Identity.psk(peerAddress, senderIdentity.getName());
            } else if (senderIdentity instanceof RawPublicKeyIdentity) {
                PublicKey publicKey = ((RawPublicKeyIdentity) senderIdentity).getKey();
                return Identity.rpk(peerAddress, publicKey);
            } else if (senderIdentity instanceof X500Principal) {
                // Extract common name
                Matcher endpointMatcher = Pattern.compile("CN=.*?,").matcher(senderIdentity.getName());
                if (endpointMatcher.find()) {
                    String x509CommonName = endpointMatcher.group().substring(3, endpointMatcher.group().length() - 1);
                    return Identity.x509(peerAddress, x509CommonName);
                } else {
                    return null;
                }
            }
        }
        return Identity.unsecure(peerAddress);
    }

returns null ...

Even fixing the above, null may be accidently introduced by someone somewhere. 
So, I think, we should Introduce a SYSTEM Identity ...

**Comment by sbernard31** [comment]
We can do that, this is probably cleaner.
You think about something like that ?
```java
public class Identity {
    public static final Identity SYSTEM = new Identity();
    ....
```

**Comment by boaks** [comment]
I introduced a ExtendedIdentity for easier distinguish between `SYSTEM,` `BOOTSTRAP_SERVER` and `DM_SERVER.`
I'm not sure, if the server works well with the return null Identity. But though I don't wan't to change this also, I chose the client side extension of the Identity.

**Comment by boaks** [comment]
I will reformat it ...

**Comment by boaks** [comment]
So, no I hope, the format is proper ...

(By the way, I'm back on tuesday :-)  )

**Comment by boaks** [comment]
Sorry, I killed you comments ;-).

Yes, a warning may be added (I hope, this comment was at the "missing common name in x509")

I chose `ExtendedIdentity,` because `SYSTEM` is no "Server"

**Comment by boaks** [comment]
Warning added, but now its late for me.
So tuesday ...

**Comment by sbernard31** [comment]
No problem ;)
(I continue to comment the PR)

**Comment by sbernard31** [comment]
Why do you want to rebase ?

**Comment by boaks** [comment]
Because the master was updated?
Or do you just wait, until conflicts are reported?

**Comment by sbernard31** [comment]
I propose to not rebase, when we will be ok about the PR. We will resolve conflicts later.

**Comment by sbernard31** [comment]
Sounds Good (Except ExtendedIdentity name  ^^ )

**Comment by boaks** [comment]
I already renamed it.
I will push soon (this afternoon).

**Comment by boaks** [comment]
If it's OK, I would rebase?

**Comment by sbernard31** [comment]
I did it. 
This is integrated in master (commit c5f03e19ba3760d7a5480cf9c2f12daa8c78ddc7)
Thx @boaks  ;)

**Pull request closed without merging**
