### PR TITLE
upload firmware update file from disk to transfer to device

### PR DESCRIPTION
**Pull request by talkjoey**

### CODE REVIEW

**Comment by sophokles73** [comment]
Hi @talkjoey,

thanks for submitting the Pull Request. However, in order for us to be able to merge it, you will need to sign an [Eclipse Contributor License Agreement](https://projects.eclipse.org/user/sign/cla) and the include a *Signed-off-by* footer in your commit message(s) using the same email address you signed the CLA for.

**Comment by sbernard31** [comment]
Hi @talkjoey,
I not sure to understand where you want to go with this PR, I suppose you propose to add Firmware update to leshan-standalone and leshan-client-example, but this deserve more explanation.

I take a look at the PR, and here is list of main issues :
 - model modification not compliant with the spec (firmware Update issue).
 - addition of  custom object in model (heart beat)
 - if you want to propose PR for Firmware Update, Heat beat feature should not be part of this PR.
 - there is a lot of duplicate code (LeshanStandalone, EventServelet ...))
 - there is a lot of commented code
 - unnecessary changes of configuration file (pom.xml, log4j.xml)
 ...
So we can not integrated this in this state, but we can start a discussion :).

**Comment by sbernard31** [comment]
I close this PR, as we can not integrated it like that, but do not hesitate to reopen it and discuss with us if you are ready to work on it.

**Comment by sbernard31** [comment]
I create an issue about firmware update #70. You could have a look if you want.

**Pull request closed without merging**
