### PR TITLE
SenML JSON decoder in leshan-core with unit tests.

### PR DESCRIPTION
**Pull request by cavenaghi9**
Contributing SenML JSON. Implementing SenML-JSON decoder in leshan-core inspired by LwM2mJson, with unit tests.

### CODE REVIEW

**Comment by sbernard31** [comment]
:+1: 

Any reason why you didn't push your commit over 2.0.x branch ?

**Comment by cavenaghi9** [comment]
> 👍
> 
> Any reason why you didn't push your commit over 2.0.x branch ?

Thanks for reminder, my earlier PR had a dependency with cf M13, that was the reason why I started everything from there. For now, I agree with you, it should commit to 2.0.x

**Comment by cavenaghi9** [comment]
I saw you have merge to 2.0.x branch, is that everything ok for you to close this PR? And I will work on rest PRs based on 2.0.x branch.

**Comment by sbernard31** [comment]
> I saw you have merge to 2.0.x branch.

Not really, I did nothing about this PR. Maybe you read too quickly and mixed encoder and decoder  ? :wink: 

Anyway I just cherry picked your commit in 2.0.x branch (so this PR is integrated commit 657eff7)

Thx again !

**Pull request closed without merging**
