### PR TITLE
SecurityRegistryImpl file persistance refactoring

### PR DESCRIPTION
**Pull request by oflisback**
This is a refactorization suggestion for SecurityRegistryImpl file persistance which looked quite wonky. If the patch has potential, please suggest approach for testing it. Currently the file persistance part of SecurityRegistryImpl isn't covered by the integration tests.

Specifically the previous implementation writes to the file while in a loop reading objects from it (loadFromFile did add which did saveToFile), it also had some funky tripple-nested exception handling.

### CODE REVIEW

**Comment by jvermillard** [comment]
Agree on the wonkyness, now why keep "concurrent hashmap" if we use synchronize ?
I would prefer two "normal" maps and a ReadWrite lock. WDYT?

This class is not tested because it's used for running leshan-demo, it's not mean to be used in production (at least we are not for AirVantage), but the location (server-core) and the doc is not explicit.

So yes, let's fix it.

**Comment by sbernard31** [comment]
I agree if we use synchronize we don't need concurrent hashmap anymore.

I'm ok that load/save method are a bit strange, I rewrote it for the [BootstrapStoreImpl](https://github.com/eclipse/leshan/blob/master/leshan-bsserver-demo/src/main/java/org/eclipse/leshan/server/bootstrap/demo/BootstrapStoreImpl.java#L87), but I don't take time to apply this change to `SecurityRegistryImpl`.

Adding `SecurityInfo[]` and `filename` to load and save method seems not really necessary? what is the purpose ?
You missed to close the `FileInputStream` in `loadFromFile`.

**Comment by oflisback** [comment]
Thanks a lot for your feedback, I have pushed an update based on your comments. I reverted the changes to the saveToFile/loadFromFile method signatures too, I prefer input parameters but I agree it wasn't a necessary change.

**Comment by sbernard31** [comment]
Currently, the file creation is done on load. I think we should do it on save, like we do [here](https://github.com/eclipse/leshan/blob/master/leshan-bsserver-demo/src/main/java/org/eclipse/leshan/server/bootstrap/demo/BootstrapStoreImpl.java#L87). We can copy/paste a large part of the save/load method.

**Comment by oflisback** [comment]
Agreed, actually this is how it's done in the current patch. :)

**Comment by sbernard31** [comment]
you're right ^^ !
I integrated you patch in master (commit 4a00f36ec47ef7d5acdb3a110b836cfea680aa0e).
I just change a log.info to log.debug.
And merge all the catching exception in one clause.
Thx @oflisback

**Comment by oflisback** [comment]
Thanks guys!

**Pull request closed without merging**
