### PR TITLE
- fix Lwm2mNodeTextEncoder for ResourcInstance

### PR DESCRIPTION
**Pull request by zakharenkodmytro**
- fixed write in BaseInstanceEnabler
- added tests

Signed-off-by: Dmytro Zakharenko <amidum@gmail.com>

### CODE REVIEW

**Comment by sbernard31** [comment]
@zakharenkodmytro thx a lot :pray:

Is there more known bug ? and so more PR incoming ?
Do you still need a 2.0.0-M1 version ?

**Comment by sbernard31** [comment]
(I edited the commit description commit integrated in master : 6948515c965233b0768f820075a98e22e5387bd9)

**Comment by zakharenkodmytro** [comment]
> @zakharenkodmytro thx a lot 🙏
> 
> Is there more known bug ? and so more PR incoming ?
> Do you still need a 2.0.0-M1 version ?

I dont think so, so far no more issues were found by me.
Yes we do need  2.0.0-M1 version, for now Im just using snapshot version.

Thanks

**Comment by sbernard31** [comment]
@zakharenkodmytro, If you think the current `master` state  is OK for you, I can do a release as soon as I get your green light.

**Comment by zakharenkodmytro** [comment]
> @zakharenkodmytro, If you think the current `master` state is OK for you, I can do a release as soon as I get your green light.

That's will be awesome. I using master branch from September 2 or around. I will do testing today with current master branch to see if it is OK, will let you know.

**Comment by zakharenkodmytro** [comment]
Hi @sbernard31 ,
During running configuration server with latest 2.0.0-SNAPSHOT I found next error 
`"exception": [{
		"message": "class "
		org.eclipse.leshan.server.security.SecurityStore "'s signer information does not match signer information of other classes in the same package",
		"file": "java.lang.ClassLoader",
		"linenumber": "1150",
		"method": "checkCerts"
	}, {
		"message": "class "
		org.eclipse.leshan.server.security.SecurityStore "'s signer information does not match signer information of other classes in the same package",
		"file": "java.lang.ClassLoader",
		"linenumber": "905",
		"method": "preDefineClass"

`
Any clue what can be wrong on my side?

Thank you
Dima

**Comment by sbernard31** [comment]
It sounds to be a jar signature issue :

Deployed Leshan jar are signed.  
This error could happen, if there are 2 classes from same package but with different signature.  
Generally this happens when you have 2 same package in 2 different jars.

Is it possible that you mix 2.0.0-SNAPSHOT jar from different source ? or your mixed 2.0.0-SNAPSHOT version with another version of Leshan ?

**Comment by zakharenkodmytro** [comment]
> It sounds to be a jar signature issue :
> 
> Deployed Leshan jar are signed.
> This error could happen, if there are 2 classes from same package but with different signature.
> Generally this happens when you have 2 same package in 2 different jars.
> 
> Is it possible that you mix 2.0.0-SNAPSHOT jar from different source ? or your mixed 2.0.0-SNAPSHOT version with another version of Leshan ?

Might be, we have a lot lib dependencies so maybe somewhere I used another version of snapshot. I will check, anyway I think you good to go with release, what do you think?

**Comment by sbernard31** [comment]
We integrated unsigned intege support in this release but it seems there is some missing part #899.
If is it OK for you, I would prefer to integrate this before the release.
This should not be so impacting.

**Comment by zakharenkodmytro** [comment]
> We will integrate unsigned intege support in this release but it seems there is some missing part #899.
> If is it OK for you, I would prefer to integrate this before the release.
> This should not be so impacting.

Absolutely, please feel free to integrate this part, i have no objections.

**Comment by sbernard31** [comment]
Watch : https://search.maven.org/search?q=g:org.eclipse.leshan%20AND%20a:leshan
2.0.0-M1 should be available in next hours.

**Comment by zakharenkodmytro** [comment]
> > We will integrate unsigned intege support in this release but it seems there is some missing part #899.
> > If is it OK for you, I would prefer to integrate this before the release.
> > This should not be so impacting.
> 
> Absolutely, please feel free to integrate this part, i have no objections.



> Watch : https://search.maven.org/search?q=g:org.eclipse.leshan%20AND%20a:leshan
> 2.0.0-M1 should be available in next hours.

Great, it is there !!! Thanks a lot, where I can find release notes?
Dima

**Comment by sbernard31** [comment]
If there is no surprise, I should do it today.

**Comment by sbernard31** [comment]
Release notes : https://github.com/eclipse/leshan/releases/tag/leshan-2.0.0-M1

**Comment by sbernard31** [comment]
@zakharenkodmytro, just in case you missed it and you want to share : https://github.com/eclipse/leshan/issues/830 :wink:

**Comment by zakharenkodmytro** [comment]
> @zakharenkodmytro, just in case you missed it and you want to share : #830 😉

Absolutely, added!

**Comment by sbernard31** [comment]
:pray: !!
Could I add verizon as Leshan adapter here : https://www.eclipse.org/leshan/#who%20is%20using ?

**Comment by zakharenkodmytro** [comment]
> 🙏 !!
> Could I add verizon as Leshan adopter here : https://www.eclipse.org/leshan/#who%20is%20using ?
Yes, definitely, please add.

**Comment by zakharenkodmytro** [comment]
Hi @sbernard31 , I integrated release to my services and so far all looks good, no issues found :) I will let you know if some bugs will discover. Thanks again

**Comment by sbernard31** [comment]
I just discover there is the same bug for JSON. (see https://github.com/eclipse/leshan/issues/913)
I will fix it.

**Pull request merged**
