### PR TITLE
Made executors configurable.

### PR DESCRIPTION
**Pull request by MKremserBosch**
Making executors configurable to be consistent through out leshan.
Signed-off-by: Michael Kremser <Michael.Kremser@bosch-si.com>

### CODE REVIEW

**Comment by balsmn** [comment]
@MKremserBosch could you please resolve the conflicts here.

**Comment by MKremserBosch** [comment]
@sbernard31 could you please merge this PR into the master before the planned release.

**Comment by sbernard31** [comment]
I can imagine how you can use your own `ScheduledExecutorService` for `InMemmoryRegistrationStore` using `LeshanBuilder`, but how do you use the new `CaliforniumLwM2mRequestSender` constructor ?

**Comment by MKremserBosch** [comment]
@sbernard31 we use the second constructor to use our own executor (for tenant logging) - to be downward compatible we have the first constructor.

**Comment by sbernard31** [comment]
I meant how could you create your `LeshanServer` with this custom `CaliforniumLwM2mRequestSender` ?

**Comment by MKremserBosch** [comment]
@sbernard31 we build our own LeshanServer with a proper Builder using a setter for the lwM2mRequestSender.

**Comment by sbernard31** [comment]
Ok. Did you modified the LeshanServer a lot ? or just to be able to have a custom LwM2MRequestSender ? Could you show us your LeshanServer version. I would like to see if it makes sense to modify the code to avoid you to duplicate LeshanServer and LeshandBuilder.

**Comment by MKremserBosch** [comment]
@sbernard31 our builder sets the following members:
        private ClientRegistry clientRegistry;
        private ObservationRegistry observationRegistry;
        private LwM2mRequestSender requestSender;
        private Lwm2mClientRegistryListener lwm2mClientRegistryListener;
        private CoapServer coapServer;

**Comment by sbernard31** [comment]
Ok I can see why you need a custom ~ClientRegistry and ObservationRegistry~ RegistrationStore.

For the ~Lwm2mClientRegistryListener~ RegistrationListener, why not using : 
```java
lwServer.getRegistrationService().addListener(listener);
```

About coapServer, You can just get it and modify it after the LeshanServer creation :
```java
LeshanServer lwServer = builder.build();
lwServer.getCoapServer().add(new MyResource());
lwServer.start();
```

**Comment by sbernard31** [comment]
@MKremserBosch  I hope I didn't annoy you too much with my questions, I just want to understand your use case and see if we can limit code duplication.

**Comment by MKremserBosch** [comment]
@sbernard31 No Problem

**Comment by sbernard31** [comment]
Ok but you didn't really answer to my questions :p so I'm not sure what is the better thing to do...
I will probably integrate your PR if that can help at short term .

**Comment by sbernard31** [comment]
The `RegistrationStore` part is integrated in master (commit 5aaef6a5cb2a6885f7c1f6c2aca1c4bd9040853d) the `Sender` part is no more needed since #256.

**Pull request closed without merging**
