### PR TITLE
add factory for object instance creation at client side

### PR DESCRIPTION
**Pull request by sbernard31**
After [discussion](https://github.com/eclipse/leshan/commit/7ad1b7c9611c3ed086e1a511b33e597c855a76d1#commitcomment-13922970), I add a factory to create object instance.

### CODE REVIEW

**Comment by jschloman** [comment]
It might also be useful to add this into the leshan-client-example as I think this would be a useful feature to demonstrate to users.

**Comment by sophokles73** [comment]
I think the classes in `org.eclipse.leshan.client.resource` could use some JavaDoc as well explaining the underlying concepts and some example code snippets ... :-) I will try to add some during the weekend ...

**Comment by sbernard31** [comment]
Should I merge this one ?

**Comment by sophokles73** [comment]
@sbernard31,

I like your latest changes which exactly reflect my thinking :-)
I have added some JavaDoc to `LwM2mInstanceEnabler` as a starting point for more to come.
However, I think you should go ahead and merge this to master now ... Maybe squashing the multiple commits into one or two before?

**Comment by sbernard31** [comment]
I merged it in master (commit 9daf45b48aeea1ce3094ffe33eeb85920e4cafd1)
Thx for the feedbacks :)

**Pull request closed without merging**
