### PR TITLE
fix parsing of float attributes values

### LINKED ISSUE #1427: DoubleAttributeModel throws InvalidAttributeException parsing valid float attribute value
### Version(s)

v2.0.0-M11

### Which components

leshan-core

### Tested With

_No response_

### What happened

```
             LwM2mCoapResource 2023-03-17 22:40:05,097 [DEBUG] Invalid request [CON-PUT    MID=61734, Token=FCA4E601, OptionSet={"Uri-Host":"172.17.0.1", "Uri-Port":56429, "Uri-Path":["6","0","0"], "Uri-Query":["pmin=7200","pmax=7200","st=1.000000"]}, <empty data>] received on the resource /6 from Identity /172.17.7.91:5683[unsecure]  
org.eclipse.leshan.core.link.attributes.InvalidAttributeException: Unable to parse [1.000000] : unexpected character '.', expected 'DIGIT' after 1
```

that value (`1.000000`) is clearly correct according to OMA-TS-LightweightM2M_Core-V1_2-20201110-A which lists the format as `1*DIGIT ["." 1*DIGIT]`.

### How to reproduce

_No response_

### Relevant Output

_No response_

### PR DESCRIPTION
**Pull request by Spongman**
fixes #1427

### CODE REVIEW

**Comment by jvermillard** [comment]
looks like a bug :blush: Do you mind completing the test case to cover your case with a float attribute?

**Comment by sbernard31** [comment]
(The build should be fixed in `master`)

**Comment by sbernard31** [comment]
:construction: @Spongman, I will start to work on this :construction: 

(Stop me if you prefer to do it by yourself)

**Comment by sbernard31** [comment]
This is integrated in #1431.

Thx again @Spongman for reporting that. (It's really appreciated)

**Pull request closed without merging**
