### PR TITLE
clinet-cf add writeAttributes support

### PR DESCRIPTION
**Pull request by dellzhui**
clinet-cf add writeAttributes support

### CODE REVIEW

**Comment by sbernard31** [comment]
@dellzhui If you open another PR I will clearly decide to ban you !

**Comment by dellzhui** [comment]
Hi Simon，
    So sorry for that.
    I thought it had been given to the robot to detect that I did not
accept the Eclipse protocol, so I repeated the submission many times.
    Back to the original reason for this PR，I think it is necessary to
support writeAttributes on the client side.
    As you see in the client demo
class(org.eclipse.leshan.client.demo.LeshanClientDemo),it creates object
instance named RandomTemperatureSensor(3303) by using
ObjectsInitializer.java, however, the method named createNodeEnabler in
ObjectsInitializer returns a LwM2mObjectEnabler object which implemented by
ObjectEnabler which extended from BaseInstanceEnabler.
    Regrettably, there is no real implementation of this method named
writeAttributes。
    So I have implemented it.
    Similarly, I added support for wirteAttributes in the
LwM2mInstanceEnabler interface.

    Next are the results of my tests：

    1.I simulate writeAttributes request in postman
[image: image.png]

2.I got this logs:
16:12:51.026 [CoapServer(main)#1] INFO
org.eclipse.leshan.client.demo.RandomTemperatureSensor - write pmax 30000
for resourceId 5750

**Comment by dellzhui** [comment]
> Hi Simon， So sorry for that. I thought it had been given to the robot to detect that I did not accept the Eclipse protocol, so I repeated the submission many times. Back to the original reason for this PR，I think it is necessary to support writeAttributes on the client side. As you see in the client demo class(org.eclipse.leshan.client.demo.LeshanClientDemo),it creates object instance named RandomTemperatureSensor(3303) by using ObjectsInitializer.java, however, the method named createNodeEnabler in ObjectsInitializer returns a LwM2mObjectEnabler object which implemented by ObjectEnabler which extended from BaseInstanceEnabler. Regrettably, there is no real implementation of this method named writeAttributes。 So I have implemented it. Similarly, I added support for wirteAttributes in the LwM2mInstanceEnabler interface. Next are the results of my tests： 1.I simulate writeAttributes request in postman [image: image.png] 2.I got this logs: 16:12:51.026 [CoapServer(main)#1] INFO org.eclipse.leshan.client.demo.RandomTemperatureSensor - write pmax 30000 for resourceId 5750



> @dellzhui If you open another PR I will clearly decide to ban you ! Please let discuss before. 🙏 ==> [#1327 (comment)](https://github.com/eclipse/leshan/pull/1327#issuecomment-1283570204) ==> [#1328 (comment)](https://github.com/eclipse/leshan/pull/1328#issuecomment-1283578841)



> @dellzhui If you open another PR I will clearly decide to ban you ! Please let discuss before. 🙏 ==> [#1327 (comment)](https://github.com/eclipse/leshan/pull/1327#issuecomment-1283570204) ==> [#1328 (comment)](https://github.com/eclipse/leshan/pull/1328#issuecomment-1283578841)

Hi Simon，
    So sorry for that.
    I thought it had been given to the robot to detect that I did not
accept the Eclipse protocol, so I repeated the submission many times.
    Back to the original reason for this PR，I think it is necessary to
support writeAttributes on the client side.
    As you see in the client demo
class(org.eclipse.leshan.client.demo.LeshanClientDemo),it creates object
instance named RandomTemperatureSensor(3303) by using
ObjectsInitializer.java, however, the method named createNodeEnabler in
ObjectsInitializer returns a LwM2mObjectEnabler object which implemented by
ObjectEnabler which extended from BaseInstanceEnabler.
    Regrettably, there is no real implementation of this method named
writeAttributes。
    So I have implemented it.
    Similarly, I added support for wirteAttributes in the
LwM2mInstanceEnabler interface.

    Next are the results of my tests：

    1.I simulate writeAttributes request in postman
[image: image.png]

2.I got this logs:
16:12:51.026 [CoapServer(main)[#1](https://github.com/eclipse/leshan/pull/1)] INFO
org.eclipse.leshan.client.demo.RandomTemperatureSensor - write pmax 30000
for resourceId 5750

**Comment by sbernard31** [comment]
> So sorry for that.

No problem, we finally succeed to start a discussion. 

Let's try to start to work in a clearer way.

Firstly please try : 
- to avoid duplicate comments :point_up:,
- try to format it correctly, (markdown is easy to learn and github preview or edit comment feature is great...)
- avoid images if this is now strictly needed...  better to copy/paste text.
- if you are using image ensure that your comment really contains the image ...

> I thought it had been given to the robot to detect that I did not
accept the Eclipse protocol, so I repeated the submission many times.

To fix your PR you don't need to create a new one, this would be a silly process...
Just push again in same branch (using `push` or `push --force`) and this will re-trigger PR checks.
But better to make it green on you development machine first using `mvn clean install javadoc:javadoc` locally.

> Back to the original reason for this PR，I think it is necessary to
support writeAttributes on the client side.

It seems you also comment at : https://github.com/eclipse/leshan/issues/534#issuecomment-1283620776
So let continue to talk about that there.

**Pull request closed without merging**
