### PR TITLE
Observe buttons for instance level

### PR DESCRIPTION
**Pull request by jvermillard**

### CODE REVIEW

**Comment by sbernard31** [comment]
I fix some little issues. If it's ok I integrate this in master in one commit ?

**Comment by sophokles73** [comment]
I am glad we have some people on board who know their JavaScript ;-)
+1 for merging in one commit

**Comment by sophokles73** [comment]
:-)

**Comment by sbernard31** [comment]
Integrated in master (commit ff1ce39f49562e87f871c32fee5ad0bcb4058959)

**Pull request closed without merging**
