### PR TITLE
Update to californium 2.0.0 M8.

### PR DESCRIPTION
**Pull request by boaks**
Adjust for modified ObservationStore API.
Remove/replace Key by Token.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by boaks** [comment]
Adjust the stores for the new ObservationStore API, I got aware, that `tokensByRegId` didn't check, if the token is already in the list. Is this intended?

**Comment by boaks** [comment]
```
                if (!tokensByRegId.containsKey(registrationId)) {
                    tokensByRegId.put(registrationId, new ArrayList<Token>());
                }
                tokensByRegId.get(registrationId).add(token);

```

the add in the last line is always executed.

**Comment by sbernard31** [comment]
You're right we should check it, or use a Set instead of a List.

**Comment by boaks** [comment]
See #477

**Pull request closed without merging**
