### PR TITLE
Fix TLV identifier serialization and COAPs support

### PR DESCRIPTION
**Pull request by lulf**
* Current head build does not work at all with setting COAPIFACES, as the value is not propagated to the correct setter
* TLV identifiers in the range 8-16 bit are not serialized according to spec.

### CODE REVIEW

**Comment by sbernard31** [comment]
Thx  luif :)
 Could you please [sign the eclipse CLA](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Eclipse_Foundation_Contributor_License_Agreement) and [sign your commits](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#The_Commit_Record) too.

**Comment by lulf** [comment]
Right, I'll have to open a new pull request, since I see that i committed with wrong email account.

**Comment by sbernard31** [comment]
In this case you can change your commit (e.g. with interactive rebase), then do a push force in your banch, (but close the pull-request and open a new one is ok too)

**Comment by lulf** [comment]
See https://github.com/eclipse/leshan/pull/38

**Pull request closed without merging**
