### PR TITLE
Backport: error handling for unexpected error in DefaultRegistrationEngin (modified)

### PR DESCRIPTION
**Pull request by sbernard31**
This is just a little bit modified version of #944

### CODE REVIEW

**Comment by sbernard31** [comment]
@moznion  does it look good to you ?

**Comment by moznion** [comment]
@sbernard31 Looks good to me. Thank you for doing this!

**Comment by sbernard31** [comment]
Ok I will integrate this in `1.x`
Is there something else you wanted to add in a 1.3.0 version ? 
Once this will be merged do you want to play this the branch 1.x to see if there is any issue before I release the 1.3.0 ?

**Comment by moznion** [comment]
Perfect ✨ 
That’s all of my wanted feature. I’m looking forward to see version 1.3.

Many thanks for your supporting!

**Comment by sbernard31** [comment]
Thx to you for the contribution.

Could I ask how you are currently using Leshan ? 
If I do the release begin of the next week is it OK to you ?

**Comment by moznion** [comment]
Yeah, it's not rushing. There is no problem for the release schedule.

> Could I ask how you are currently using Leshan ?

Yes, we are using Leshan (I appreciate this project!). Shall I let you know that at #830 ?

**Comment by sbernard31** [comment]
>  Shall I let you know that at #830 ?

That would be great :)

**Comment by sbernard31** [comment]
(oh just in case you missed this, there are nightly build released on eclipse maven repository, so a release 1.3.0-SNAPSHOT is already available look at [README](https://github.com/eclipse/leshan/blob/master/README.md) for more details)

**Comment by moznion** [comment]
Thank you for the information :)

**Comment by sbernard31** [comment]
@moznion, thx for adding a comment on #830 :pray:
Could I also add your company as Leshan adopters : https://iot.eclipse.org/adopters/#iot.leshan ?

**Comment by moznion** [comment]
@sbernard31 Yes, please 🙏

**Comment by sbernard31** [comment]
@moznion v1.3.0 is out : https://github.com/eclipse/leshan/releases/tag/leshan-1.3.0

**Comment by moznion** [comment]
🎉 
I appreciate your hard work, @sbernard31 !!

**Pull request merged**
