### PR TITLE
Added ResponseCode.SERVICE_UNAVAILABLE

### PR DESCRIPTION
**Pull request by bolddp**
Signed-off-by: Daniel Persson <bighatsmallfeet@gmail.com>

### CODE REVIEW

**Comment by sbernard31** [comment]
I look at the lwm2m spec and this is not a response code explicitly accepted.

Currently, we are pretty strict on that, but maybe it's not a good idea.

Before to make a decision, I would like to better understand your problem with the current version and what will change with this fix ? (are you using Leshan Client or Server ?)

**Comment by bolddp** [comment]
One of our first implemented real-world Lwm2m clients are using the con-tiki stack, where the Observe pattern still needs some work to be less memory-consuming. You can set a constant that states how many simultaneous observes you accept as a client, and when the server sends a new observe request that will exceed that limit, the con-tiki stack responds with 503 Server unavailable. So the main usage is on the server side, but we're also interested in being able to simulate this behavior in our client simulator.

**Comment by sbernard31** [comment]
I see with your change you should be able to create to simulate this 503 error at client side but at server side you will still have a InvalidResponseException because of [LwM2mResponseBuilder](https://github.com/eclipse/leshan/blob/master/leshan-server-cf/src/main/java/org/eclipse/leshan/server/californium/impl/LwM2mResponseBuilder.java#L235).

Am I right ?

**Comment by bolddp** [comment]
Yes, it looks like I missed that. I haven't yet had a chance to try it out fully, I'm still trying to figure out how I can allow our corporate leshan clone (with internal modifications related to the build environment etc.) to play nicely with changes that I think could be of value to the eclipse/leshan master. And I'm no expert on GIT, as you may have noticed from the earlier pull requests attempts...

But if you think that we should include graceful handling of 503, it looks like we need to update the LwM2mResponseBuilder as well.

**Comment by sbernard31** [comment]
I rethink about that and the way we do in leshan is clearly to strict. I will search for another solution, I would like to handle all unknown code not only 503.
Once I have something "showable", I will shared it with you and you let me know if this fits your need.
Does it sounds good for you ?

**Comment by bolddp** [comment]
Yes, I'd be glad to provide feedback.

**Comment by sbernard31** [comment]
#399 in now integrated in master, so we can close this PR.

**Pull request closed without merging**
