### PR TITLE
Allow for interaction between a program using the leshan-client and the ...

### PR DESCRIPTION
**Pull request by jschloman**
...object instances it creates.  This is demonstrated in the example by allowing the a user to set the error code via the console.

Signed-off-by: John Schloman <jschloman@zebra.com>

### CODE REVIEW

**Comment by jschloman** [comment]
Simon,

I've finally pushed through the simple as possible approach.  I put in some runtime exceptions so that the user doesn't inadvertently setClassForObject() and setInstanceForObject() on the same object.  I then added a simplistic Location object instance in the example to demonstrate how to use this.  Hopefully this should give the users the flexibility they need.

-JF

**Comment by sbernard31** [comment]
John,
 I'm in vacation for 2 weeks, I will look at this when I will be back.

**Comment by sbernard31** [comment]
It seems ok for the `setInstanceForObject` :) !
But now we can set an instance at initialization, we don't need the listener in the `ObjectsInitializer` anymore ?

(Not linked to this issue but I see my code is bugged  in `createNodeEnabler` ...  we should not  always create an `ObjectEnabler` with the `SimpleInstanceEnabler.class` as parameter, we should use the class in the `classes` map or the class of the instance we  just created.)

**Comment by jschloman** [comment]
I'm wondering if it would still be useful to keep the listener:  in the case of a resource that allows multiple instances, it might be preferable for the device using the library to keep track of all instances created by the server?

Also there is the issue on the leshan-dev mailing list about parameters not being passed for ExecuteRequests.  I responded with where I think the issue is in the code... maybe it would be worthwhile to sneak that into this PR as well?

(Sorry for the late reply.  I'm on vacation right now and have intermittent internet access).

-J

**Comment by sbernard31** [comment]
I think we probably need listener for instance creation but this should be managed at `ObjectEnabler` level.
(not in `ObjectsInitializer`, even if we can imagine that `ObjectsInitializer` could add listener on `ObjectEnabler`)

For the issue in the mailing list, you get right I fixed it and add the UI in standalone to be able to send execute request with parameters. I preferred having this changes in a separated commit.

**Comment by jschloman** [comment]
OK so I've removed all of the listener work and now just allow for adding of the instance to use.

**Comment by sbernard31** [comment]
I integrated this in master (I remove some unused import)
I fix the bug I talked about previously in another commit.
This should be more usable now :D
(thx john)

**Pull request closed without merging**
