### PR TITLE
Contentformat senml

### PR DESCRIPTION
**Pull request by cavenaghi9**
application/senml+json and application/senml+cbor, implementation has dependency with cf-2.0.0-M13.

### CODE REVIEW

**Comment by sbernard31** [comment]
Thx for the contribution.

First step for a contribution to an eclipse project, the legal stuff  ... 
Here more details about it : https://github.com/eclipse/leshan/wiki/How-to-contribute#legal-stuff-

Is it OK for you ?

**Comment by cavenaghi9** [comment]
> Thx for the contribution.
> 
> First step for a contribution to an eclipse project, the legal stuff ...
> Here more details about it : https://github.com/eclipse/leshan/wiki/How-to-contribute#legal-stuff-
> 
> Is it OK for you ?

I had signed ECA few month ago, and I sign-off just now.

**Comment by sbernard31** [comment]
I looked at this PR quickly and It will be hard to review it and integrate it like this (too big, commit cherry picked from master, ...)

I propose to cut this contribution in several smaller PR : 
1. contributing **SenML-JSON** encoder in `leshan-core` inspired by `LwM2mJson`  + unit tests (at least spec examples)
2. contributing **SenML-JSON** decoder in `leshan-core` inspired by `LwM2mJson`  + unit tests (at least spec examples)
3. contributing `LwM2mNodeSenMLEncoder` for **SenML-JSON** + unit tests
4. contributing `LwM2mNodeSenMLDecoder` for **SenML-JSON** + unit tests
5. add **SenML-JSON** content format + encoder to `DefaultLwM2mNodeEncoder`.
6. contributing **SenML-CBOR** encoder in `leshan-core`   + unit tests (at least spec examples)
7. contributing **SenML-CBOR** decoder in `leshan-core`   + unit tests (at least spec examples)
8. contributing `LwM2mNodeSenMLEncoder` for **SenML-CBOR** + unit tests
9. contributing `LwM2mNodeSenMLDecoder` for **SenML-CBOR** + unit tests
10. add **SenML-CBOR** content format + encoder to `DefaultLwM2mNodeEncoder`.
11. add **SenML-JSON** + **SenML-CBOR** to leshan demo.

Does it make sense to you ?
(If you are ok, do not forget to sign all your future commit)

**Comment by cavenaghi9** [comment]
> I looked at this PR quickly and It will be hard to review it and integrate it like this (too big, commit cherry picked from master, ...)
> 
> I propose to cut this contribution in several smaller PR :
> 
>     1. contributing **SenML-JSON** encoder in `leshan-core` inspired by `LwM2mJson`  + unit tests (at least spec examples)
> 
>     2. contributing **SenML-JSON** decoder in `leshan-core` inspired by `LwM2mJson`  + unit tests (at least spec examples)
> 
>     3. contributing `LwM2mNodeSenMLEncoder` for **SenML-JSON** + unit tests
> 
>     4. contributing `LwM2mNodeSenMLDecoder` for **SenML-JSON** + unit tests
> 
>     5. add **SenML-JSON** content format + encoder to `DefaultLwM2mNodeEncoder`.
> 
>     6. contributing **SenML-CBOR** encoder in `leshan-core`   + unit tests (at least spec examples)
> 
>     7. contributing **SenML-CBOR** decoder in `leshan-core`   + unit tests (at least spec examples)
> 
>     8. contributing `LwM2mNodeSenMLEncoder` for **SenML-CBOR** + unit tests
> 
>     9. contributing `LwM2mNodeSenMLDecoder` for **SenML-CBOR** + unit tests
> 
>     10. add **SenML-CBOR** content format + encoder to `DefaultLwM2mNodeEncoder`.
> 
>     11. add **SenML-JSON** + **SenML-CBOR** to leshan demo.
> 
> 
> Does it make sense to you ?
> (If you are ok, do not forget to sign all your future commit)

Make sense, I have created first PR #659 already. However, I have to update DefaultLwM2mNodeEncoder in first commit, in order to reuse existing encoder unit test

**Comment by cavenaghi9** [comment]
Close this one, and will split into more smaller size PRs.

**Pull request closed without merging**
