### PR TITLE
Some fix about "Improved compliance with rfc6690"

### PR DESCRIPTION
**Pull request by sbernard31**
This is #1098 with some cosmetic fixes.

### CODE REVIEW

**Comment by sbernard31** [comment]
About the error, Uups I did a mistake 🤦.
I wanted to talk about : 
```
</foo>;param=<,</bar>;param=>
```
I think in this case this is valid.
But currently the code raise : 
```
org.eclipse.leshan.core.link.LinkParseException: Invalid Links [</foo>;param=<,</bar>;param=>] : invalid link-extension [param=<,</bar>] : invalid ptoken [<,</bar>]
	at org.eclipse.leshan.core.link.DefaultLinkParser.parse(DefaultLinkParser.java:68)
	at org.eclipse.leshan.core.link.DefaultLinkParserTest.parse_example_uri_references(DefaultLinkParserTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: org.eclipse.leshan.core.link.LinkParseException: invalid link-extension [param=<,</bar>] : invalid ptoken [<,</bar>]
	at org.eclipse.leshan.core.link.DefaultLinkParser.parseLinkExtension(DefaultLinkParser.java:141)
	at org.eclipse.leshan.core.link.DefaultLinkParser.parseLinkValue(DefaultLinkParser.java:92)
	at org.eclipse.leshan.core.link.DefaultLinkParser.parse(DefaultLinkParser.java:63)
	... 27 more
Caused by: org.eclipse.leshan.core.link.LinkParseException: invalid ptoken [<,</bar>]
	at org.eclipse.leshan.core.link.DefaultLinkParser.validatePtoken(DefaultLinkParser.java:212)
	at org.eclipse.leshan.core.link.DefaultLinkParser.validateLinkExtensionValue(DefaultLinkParser.java:177)
	at org.eclipse.leshan.core.link.DefaultLinkParser.parseLinkExtension(DefaultLinkParser.java:136)
	... 29 more


```

**Comment by Michal-Wadowski** [comment]
> </foo>;param=<,</bar>;param=>

Fixed :smile:

**Comment by sbernard31** [comment]
I'm not totally sure for now but I maybe find a regression.
The server-demo seems to serialize the Link Object differently and so this breaks the server-demo UI.

**Comment by Michal-Wadowski** [comment]
I fixed it in "UI fixes for new Link object" commit (https://github.com/Przem83/leshan/commit/703ffcc99ed6a2f428b179949caec7d630d8fb14)

**Pull request closed without merging**
