### PR TITLE
Implement POST "/oid/iid" as UPDATE instance

### PR DESCRIPTION
**Pull request by boaks**
Implement POST "/oid/iid" as UPDATE instance according
OMA-DM-LightweightM2M-2015-0054R02-CR_Commands_Definition_Conflicts.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by sbernard31** [comment]
Sounds good. 
We could also add some tests in `leshan-integration-tests`.
if we want to handle this correctly we should also add the code which manage `UPDATE` and `REPLACE` in [`ObjectEnabler`](https://github.com/eclipse/leshan/blob/master/leshan-client-core/src/main/java/org/eclipse/leshan/client/resource/ObjectEnabler.java#L145)

**Comment by boaks** [comment]
OK, I will add test (and remove whitespace :-) .

**Comment by boaks** [comment]
An other alternative for removing not longer contained resources in REPLACE may be the introduction of a "onInitialize" method in `BaseObjectEnabler`.

**Comment by sbernard31** [comment]
Tests is ok for me.

About `REPLACE`/`UPDATE`, I should have chosen the `DELETE`/`CREATE`.
I mean intuitively, It seems that `REPLACE` means delete the instance and replace it by this new one. (so this seems to be a creation)
With your solution we keep the previous instance.

The spec is really don't clear about this:
*" - Replace: replaces the Object Instance or the Resource(s) with the new value provided in the “Write” operation."*

But maybe you're right, your solution avoid some troubles:
- e.g. On `Server` Object a `delete`/`create` means that we will lost the shortID
- e.g. With mandatory single instance a `delete`/`create` will be problematic as a delete is forbidden (For this one we can choose to use the SYSTEM identity ...)

**If someone else has an idea about that ?**

In all case, if we chose your solution, I prefer we avoid the `write(null)` stuff and use the `DeleteRequest` on the resource.

**Comment by boaks** [comment]
I have to confess, that currently my "Objects Instances" are more "wired" and it would be very hard to change that right now to `delete` / `create` (I know, this means also no bootstrap :-) ).

I will go for a `Delete` on a resource

**Comment by boaks** [comment]
(Forget this ...

Why? Delete ("/o/i/r") works, may be a more radical then expected :-).

**Comment by boaks** [comment]
Using DELETE on resource level only for the SYSTEM and not for DM SERVER makes a dependecy to the PR #95.
It would be cleaner to use the newly introduce ExtendedIdentity.

**Comment by boaks** [comment]
After reanalysing, I choose the name `reset()` for cleanup the none mandatory writable resources in case of write / UPDATE.

For a more "far solution" I started thinking about something with
- `startWrite(update/replace)`
- `finishWrite(success/rollback)`
- `onDelete()`
on `InstanceEnabler` base.
This introduce the possibility to support 
- "atomic instance writes" (with rollback)
- collect changes for multi resources changes caused by instance writes
- may protect reads for changing instances.
- release resource, when the instance is deleted.

The issue for such a "far solution" would be, that it should have a defined
"Threading Model" (see Californium `Resource.getExecutor()` ). Otherwise
I would guess, that it may get to complicated.

**Comment by sbernard31** [comment]
Integrated in master (commit 37fb24f499269fcff4a7744407f5e7d4d343fd97)
Thx again @boaks.

**Comment by boaks** [comment]
WARNING:
The REPLACE is not proper working for Bootstrap!
It doesn't write the server ID in the server instance ...
I'm going to fix this.

**Comment by jvermillard** [comment]
:scream:

**Comment by boaks** [comment]
Yes, but usually a BS will first delete all security and server object instances.
So the REPLACE is a rare case for BS.

**Pull request closed without merging**
