### PR TITLE
fix memory leak on observation registry

### PR DESCRIPTION
**Pull request by sbernard31**
There is a memory leak on observation registry, `observationsByClientAndResource` is never cleared. This should fixed the issue.

### CODE REVIEW

**Comment by sophokles73** [comment]
I would also love to see a test case for this :-)

**Comment by sbernard31** [comment]
This is done :)

**Comment by sbernard31** [comment]
I suppose I can merge this one in master now ?

**Comment by msangoi** [comment]
:+1: for me.

**Comment by sbernard31** [comment]
integrated in master (commit 5f2a23f55217cc5e783ef1bd37ea0942dd9bf289)

**Pull request closed without merging**
