### PR TITLE
Fix leshan demo client incorrect initialization of object 3442, resou…

### PR DESCRIPTION
**Pull request by davidahoward**
…rces 120, 1120 #1352

updated public class LwM2mTestObject,
public static final Long INITIAL_INTEGER_VALUE = 1024l;

### CODE REVIEW

**Comment by jvermillard** [comment]
The ECA looks good, @sbernard31 any idea why the check fail?

**Comment by jvermillard** [comment]
@davidahoward did you associated your github user with your eclipse account? I suspect it's the source of the failure

**Comment by sbernard31** [comment]
I relaunch it manually and it seems it works.

@davidahoward, avoid to create several PR for same contribution. Until now I never see any issue which could not have been solved by the editing a PR (new commit or commit --ammend/ push --force).

If you didn't succeed to get :heavy_check_mark:, just ask for help. (but please do not recreate a PR)

**Comment by sbernard31** [comment]
Anyway, thx for your contribution. :pray: 

Once you think your PR is ready, click on `Ready for review` :point_up:

**Comment by davidahoward** [comment]
> I relaunch it manually and it seems it works.
> 
> @davidahoward, avoid to create several PR for same contribution. Until now I never see any issue which could not have been solved by the editing a PR (new commit or commit --ammend/ push --force).
> 
> If you didn't succeed to get ✔️, just ask for help. (but please do not recreate a PR)

yeah - sorry about that ... i was getting really frustrated with it...  i have multiple github accounts, and it looks like there was some sticky cookies or something that was pointing eclipse at another account.

**Comment by sbernard31** [comment]
This is integrated in `master` (commit `5877f57d87e81137b5dba40da4cdd03738c3651d)

(I just change the commit name header)

**Comment by sbernard31** [comment]
Thx @davidahoward for the contribution :pray:

**Pull request closed without merging**
