### PR TITLE
Fix TLV encoding for negative integer

### PR DESCRIPTION
**Pull request by msangoi**
Use signed magnitude representation instead of two's complement

### CODE REVIEW

**Comment by msangoi** [comment]
OK with Wakaama client.

**Comment by sbernard31** [comment]
Integrated in master (commit : 0e0bd6e1fdd09ddbdabed1ca0841c483d56975d5)

**Comment by msangoi** [comment]
Reverted in master with commit bbebd77bd5848449306a942cdb517fac77150bae.

Since the spec is ambiguous about the signed integer representation (Opened OMA issue: https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues/55#issuecomment-121798495), we will wait for a clarification before merging the fix.

**Comment by jvermillard** [comment]
Seems fixed in OMA-TS-LightweightM2M-V1_0-20150910-D

**Pull request closed without merging**
