### PR TITLE
Object versioning

### PR DESCRIPTION
**Pull request by bolddp**
This has been open before, but now there's also changes to the server-demo to reflect the object version in the GUI.

### CODE REVIEW

**Comment by bolddp** [comment]
I just realized that there are whitespace errors in some commits... For some reason, it seems that adding "?w=1" to the pull request URL resolves this...

**Comment by sbernard31** [comment]
About substance : 
 - modification on `leshan.core`, `leshan.client.core` and `leshan-integration-tests` seems ok !
 - modification on `leshan-server-demo` makes less sense to me. Why changing all the API to get model by registration if we use a `StaticModelProvider`. let's focus on core we will see later for demos.

About the form :
- there is formatting issue,
- unnecessary final keyword,
- all the commits are not signed,
- please rebase your work on master,
- please separate your work in several commit only if this help to review it. Here separate formatting commits do not help. 

To go further about object versioning.
We have now `ObjectModel` with version.
But `LwM2mModel` can contain only one version of an `ObjectModel`.
This is OK for a client because it can not have the same object in several version.
But at server side we want to store `ObjectModel` in several object versions. So maybe we need now 2 kind of `LwM2mModel`.
1. `LwM2mClientModel` which contain all the `ObjectModel` for 1 client.
2. `LwM2mServerModel` which contain all the `ObjectModel` in several version.

At client side we only use the `LwM2mClientModel`.
At server side `LwM2mModelProvider` will be responsible to create `LwM2mClientModel` for a given Registration from its `LwM2mServerModel`.

Maybe `LwM2mClientModel` and `LwM2mServerModel` are not great name but I can not find better ones for now.

**Comment by bolddp** [comment]
OK, thanks for the feedback!
I'll have a look at the format, it's our company programming formatting that wasn't disabled for leshan, it sets 'final' etc.

Yes, the models will probably have to be redesigned. In our project, I've written a VersionedLwm2mModelProvider, together with a ObjectModelRepository and a cache that serves up an object model based on the object versions in a registration. Only problem with that is that it can't pick object versions for object id's that aren't part of the registration, e.g. to create objects, which I haven't solved properly yet.

When do you plan to make next release? I'm swamped with other things right now, so I'm not sure when I get time to look further at this.

**Comment by sbernard31** [comment]
No planed milestone release for now. But don't worry if this is not in the next milestone, this will be in the following.

**Comment by sbernard31** [comment]
@bolddp @danielhqv we will maybe do a milestones release.
(see :https://dev.eclipse.org/mhonarc/lists/leshan-dev/msg00954.html)

Would you like to integrate this in this release ?

**Comment by danielhqv** [comment]
Sorry I've missed this thread until now. When do you plan to release the milestone?
And I'm still not sure how to sign the failing commits, it has a signed-off footer that matches an existing agreement on the Eclipse page.

**Comment by sbernard31** [comment]
If no bad surprise, I plan to release the milestone this week or the next week.
About signed commits, this is just that some commits are not signed at all.

**Comment by danielhqv** [comment]
I'm not sure how to solve this, I'm still no expert at Git / Github to say the least... This branch has already been merged into our master since we needed the changes in November. And you argue that the web parts should be completely untouched, so they would need to be reset.

Preferably I would like to reset the branch and put them in one signed commit (minus the web parts, then) and try to fix the formatting issues in this single amended commit as well.

But since there is an active pull request on this branch, wouldn't that mess things up?

**Comment by sbernard31** [comment]
Just about git and github, you can just change/(rewrite history) of branch as you want (using tools like rebase interactive, but there is many other way to do that) then just push force the same branch. That way you work will still be linked to this PR.

If you have a bad feeling about this, you can create a new PR with a new branch and we will close this one.

As you prefer.

**Comment by danielhqv** [comment]
OK, so far so good... :) Would I get rid of the conflicts by rebasing on master? And effectively I would like to bebase onto your leshan/master, I suppose, not our master?

**Comment by sbernard31** [comment]
Yes I just talk about leshan/master. (I'm not aware enough about your master branch to give you advice about that)

**Comment by danielhqv** [comment]
This is as close as I get now, I think. Can you consider adding the three edits to ObjectModelSerDes manually, if I remove it from this commit so it's mergeable? It's rows 41, 78 and 81 that adds the version field to the ser/des logic.

**Comment by sbernard31** [comment]
I will look at this.

**Comment by sbernard31** [comment]
I do not understand what was the issue with the `ObjectModelSerDes` ... It does not make sense to me that git see a conflict on the whole file ...

Anyway, I fixed this manually and integrated your PR in master (commit ccaccfdaee856789d797c279ae75d6d23b675721).

Thx @danielhqv for this contribution.

Next step a the `ObjectModelRepository` ;)

**Comment by danielhqv** [comment]
Thx a lot, and I'm glad to be able to contribute. I think that the ObjectmodelSerDes didn't exist when I created the branch, and after making a few attempts to merge your master into our, I ran out of time and ended up with this mismatch. I will perform a full merge before I create any more pull requests.

I could've removed the file from my branch to avoid the conflict, I think, but I wanted you to be able to see what changes it contained.

**Pull request closed without merging**
