### PR TITLE
Refactoring about Link Format

### PR DESCRIPTION
**Pull request by sbernard31**
This is a refactoring to try to propose a API to bound `Attribute`  and `Link` world, proposing a kind of LWM2M flavored `Link`.
Some idea are described at : 
- https://github.com/eclipse/leshan/issues/1118#issuecomment-961184229
- https://github.com/eclipse/leshan/issues/1118#issuecomment-964337947

This is an huge PR ... I really don't like to do that :disappointed:...
However I tried to make it with a series of "small" consistent commit.

I will probably squash all of this in 1 commit when integrating this in `master`.

~There are renaming work but I think this should be done in some other PRs :~ 
~- Use LwM2mLink for discover~
~- Use Version instead of String for VERSION.~
~- Add notification/properties kind to model.~
~- Add range check~
~- Add applicability check~
~- quoted version invalid by default ?~
~- Make linkparser/attribute parser configurable.~
Finally done in this PR.

### CODE REVIEW

**Comment by sbernard31** [comment]
@Michal-Wadowski I don't know maybe you want to have a look at this before I integrate it in `master` ?
(In the other hand, I could understand that you didn't want to dig in a huge PR like this :fearful:)

**Comment by Michal-Wadowski** [comment]
@sbernard31 unfortunately I have limited time recently, so I can't look at this. I believe all the changes are OK :smile:

**Comment by sbernard31** [comment]
I think this is in a mergeable state. 
I plan to integrate it in `master` on next Monday.

**Comment by sbernard31** [comment]
This is now integrated in `master` (commit 30f79d333b3bf8cd2b4e602fc5bb797f481583b5)

**Comment by nurely** [comment]
Noob here, noob to Java and everything. Somehow many stuff mentioned here is not available to the Leshan-Server-Demo. For example: 

org.eclipse.leshan.core.link.attributes does not exist. 
package org.eclipse.leshan.core.link.lwm2m.attributes does not exist

I tried clean installing.

Can somebody help me here?

When I go into details, checking out the external libraries. I do not see these files are available as it does in Master. Somehow the Maven builds are not new. If that's the case, how do I build jar directly from the master and use them in the demo server?

**Comment by sbernard31** [comment]
> Somehow many stuff mentioned here is not available to the Leshan-Server-Demo

Which version are you talking about ? (where/how do you get your "leshan-server-demo" ?

Currently there is no (stable or milestone) release which integrate this. This is available in `master`.
To build from `master` : https://github.com/eclipse/leshan#compile-leshan--run-demos

HTH

**Comment by sbernard31** [comment]
You can also download the already built jar of `master` looking at the https://github.com/eclipse/leshan#readme table (leshan v2.0.x)

**Pull request closed without merging**
