### PR TITLE
Reuse already unmodifiable map of additional registration attributes.

### PR DESCRIPTION
**Pull request by boaks**
Creating a "unmodifiable map" with each registration update will build a
very long list of unmodifiable map (see current implementation of
Collections.unmodifiableMap()). Therefore change the implementation to
create such a unmodifiable map only, if the map is not already
unmodifiable.

Signed-off-by: Achim Kraus <achim.kraus@bosch-si.com>

### CODE REVIEW

**Comment by boaks** [comment]
An alternative approach would be to change the Builder instead of using a modifiable test.

**Comment by sbernard31** [comment]
```java
if (additionalRegistrationAttributes == null || additionalRegistrationAttributes.isEmpty()) {
    this.additionalRegistrationAttributes = Collections.emptyMap();
} else {
    this.additionalRegistrationAttributes = Collections
        .unmodifiableMap(new HashMap<>(additionalRegistrationAttributes));
}
```
What  about that ?

**Comment by boaks** [comment]
The empty part looks good, but why 

`Collections.unmodifiableMap(new HashMap<>(additionalRegistrationAttributes))`

?

**Comment by sbernard31** [comment]
I thought that your problem was that after several updates we will face something like an UnmodifiableMap which encapsulates and UnmodifiableMap which encapulates and UnmodifiableMap which .... which encapsulate the "real" map. (only for in memory registrationStore by the way)

This `Collections.unmodifiableMap(**new HashMap**<>(additionalRegistrationAttributes))` will avoid that.

**Comment by boaks** [comment]
Ah, OK! 
So, could/do you fix it in your way? I would appreciated that.

**Comment by sbernard31** [comment]
Ok I will do that.

**Pull request closed without merging**
